"""AUSHADHI — purchase order models.

Mirrors the `purchase_orders` collection in docs/DATABASE_SCHEMA.md.
Generated by the Procurement Agent. All timestamps are ISO 8601 UTC strings.
"""

from typing import List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

POPriority = Literal["CRITICAL", "HIGH", "MEDIUM", "LOW"]
POStatus = Literal[
    "PENDING_APPROVAL",
    "APPROVED",
    "DISPATCHED",
    "DELIVERED",
    "CANCELLED",
]


class PurchaseOrderLineItem(BaseModel):
    """A single medicine line on a purchase order."""

    model_config = ConfigDict(extra="ignore")

    medicine_id: str
    medicine_name: str
    requested_quantity: int = Field(..., ge=0)
    unit: str
    unit_cost_inr: float = Field(..., ge=0.0)
    total_cost_inr: float = Field(..., ge=0.0)
    urgency: str
    days_until_stockout: int

    def to_firestore_dict(self) -> dict:
        return self.model_dump()


class PurchaseOrder(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: str
    po_number: str

    health_center_id: str
    health_center_name: str
    district: str

    warehouse_id: str
    warehouse_name: str
    warehouse_distance_km: float = Field(..., ge=0.0)
    estimated_delivery_hours: float = Field(..., ge=0.0)

    priority: POPriority

    line_items: List[PurchaseOrderLineItem] = Field(default_factory=list)

    total_cost_inr: float = Field(..., ge=0.0)

    status: POStatus = "PENDING_APPROVAL"

    outbreak_linked: bool = False
    outbreak_alert_id: Optional[str] = None

    # ---- Approval tracking ----
    approval_required: bool = True
    approved_by: Optional[str] = None
    approved_at: Optional[str] = None
    dispatched_at: Optional[str] = None
    delivered_at: Optional[str] = None

    generated_by: Literal["AUSHADHI_PROCUREMENT_AGENT"] = "AUSHADHI_PROCUREMENT_AGENT"
    created_at: str
    updated_at: str

    def to_firestore_dict(self, exclude_none: bool = False) -> dict:
        """Firestore document body.

        Approval/dispatch/delivery timestamps are written as explicit nulls by
        default so lifecycle transitions overwrite prior values cleanly.
        """
        return self.model_dump(exclude_none=exclude_none)
